name: WhosAFK
main: whosafk.WhosAFK
version: beta-4.1

commands:
    afk:
        description: Sets your status to AFK.
        usage: /<command> to be AFK
#    whosafkcolor:
#        description: Sets the color of the WhosAFK plugin.
#        usage: /<command> [color]