name: WhosAFK
main: whosafk.WhosAFK
version: 1.2.0
author: Jasper Reddin
api-version: 1.16

commands:
  afk:
    description: Sets your status to AFK.
    usage: /<command> to be AFK
    permission: whosafk.afk
  whosafkreload:
    description: Reloads the WhosAFK configuration file.
    usage: /<command>
    permission: whosafk.reload

permissions:
  whosafk.afk:
    description: Allows player to use /afk.
    default: true
  whosafk.autoafk:
    description: Allows players to automatically go in to AFK mode.
    default: true
  whosafk.reload:
    description: Allows player to reload config.
    default: op